theme = "rose-pine"

[editor]
mouse = true
end-of-line-diagnostics = "hint"
clipboard-provider = "pasteboard"
text-width = 80

[editor.statusline]
left = ["mode", "file-absolute-path", "spinner"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true
ignore = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 500

[editor.lsp]
snippets = true

[keys.normal]
"C-j" = ["scroll_down"]
"C-k" = ["scroll_up"]
"C-r" = [":config-reload", ":reload-all", ":lsp-restart"]
"C-f" = [":format"]
"C-p" = [":sh cat '%sh{pwd}/%{buffer_name}' | pbcopy"]
"S-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"S-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.select.space]
e = [
  ':sh rm -f /tmp/unique-file',
  ':set mouse false',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse true',
]
# Show word count
A-w = "@<A-|>tee /tmp/helix-wc.file<ret>:sh cat /tmp/helix-wc.file | wc -w<ret>"

[keys.normal.space]
e = [
  ':sh rm -f /tmp/unique-file',
  ':set mouse false',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse true',
]
